services:
  dns-bind9-webadmin:
    image: sameersbn/bind:9.16.1-20200524
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "10000:10000/tcp"
    volumes:
      - "./dns_data_with_webadmin:/data"
  
  dns-bind9:
    image: ubuntu/bind9:9.18-22.04_beta
    environment:
      - TZ=UTC
    ports:
      - "10053:53"
      - "10053:53/udp"
    volumes:
      - ./bind9/etc/named.conf:/etc/bind/named.conf
      - ./bind9/etc/named.conf.options:/etc/bind/named.conf.options
      - ./bind9/etc/named.conf.local:/etc/bind/named.conf.local
      # - /path/to/cached/data:/var/cache/bind
      - ./bind9/lib:/var/lib/bind
  
  dns-coredns:
    image: coredns/coredns
    ports:
      - "20053:53/udp"
    volumes:
      - ./coredns:/root/
    command: -conf /root/Corefile